# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Changlog Updated
on: 
  pull_request:
    branches: [ master ]

jobs:
  label:

    runs-on: ubuntu-latest
    steps:
    - id: file_changes
      name: Get changed files
      uses: trilom/file-changes-action@v1.2.3
    - name: echo changes
      run: |
        echo Files
        cat $HOME/files.json
        echo Modified
        cat $HOME/files_modified.json
        echo Added
        cat $HOME/files_added.json
        echo Removed
        cat $HOME/files_removed.json
        echo Files
        echo '${{ steps.file_changes.outputs.files}}'
        echo Modified
        echo '${{ steps.file_changes.outputs.files_modified}}'
        echo Added
        echo '${{ steps.file_changes.outputs.files_added}}'
        echo Removed
        echo '${{ steps.file_changes.outputs.files_removed}}' 
    - name: List files
      run: |
        echo ${{ steps.file_changes.outputs.files_modified}}
        if [[ "${{ steps.file_changes.outputs.files_modified}}" == *"ChangLog"* ]] then
          echo "Changlog has been updated"
        else
          echo "::error file=app.js,line=10,col=15::Changelog hasnt been updated"
        fi
